### ISSUE TITLE
failed to load on  ha beta 2026.2.0b0

### ISSUE THREAD

**Issue by scooper1** [azerty9971/xtend_tuya#719]
load failure on current beta ha  2026.2.0b0
following error 
Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 21:28:35 (1 occurrence)
Last logged: 21:28:35

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

**Comment by scooper1** [comment]
This needs fixing, as going to break a lot of systems when  2026.2  is released on tuesday  
I had to revert to 2026.1 to keep my system running due to problem
It would be very good for a developer to find the issue - I am not experienced enough to find the fix

at least 6 others with the problem from reactions above 

thanks

**Comment by azerty9971** [comment]
Hello,
Can you try the latest beta (v4.3.1-beta.6) and report if it fixes the issue on 2026.2? (it should :))

Thanks in advance,
Azerty

**Comment by scooper1** [comment]
Thanks I will try tonight

**Comment by HBK1** [comment]
v4.3.1-beta.6 works with 2026.2.0b1

**Comment by scooper1** [comment]
it works for me 2026.2.0b1
thank you
ps assume you know that it breaks in 2026.1.3

**Comment by rthsw** [comment]
Hi, where can i get/find the V4.3.1? I only find resources for the V4.3.0, which is running on my HA. ... WAS running. After updating the HA this morning, nothing from xTend Tuya is running, all automations, all switches, all sensors, all automations... everything is offline.

**Comment by scooper1** [comment]
go into hacs  -> find xtend tuya  -> three dot menu -> redownload -> beta 6 has the fixes
