### ISSUE TITLE
4.3.0 init fails cannot import name '_SwingModeWrapper' from  'homeassistant.components.tuya.climate'

### ISSUE THREAD

**Issue by myTselection** [azerty9971/xtend_tuya#696]
2026-01-08 10:02:52.692 ERROR (MainThread) [homeassistant.config_entries] [2026-01-08 10:02:52,692] [ERROR] homeassistant.config_entries > Error occurred loading flow for integration xtend_tuya: cannot import name '_SwingModeWrapper' fro
m 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
2026-01-08 10:02:52.693 ERROR (MainThread) [homeassistant] [2026-01-08 10:02:52,693] [ERROR] homeassistant > Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3948, in _load_integration
    await integration.async_get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1111, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1206, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name '_SwingModeWrapper' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1462, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1500, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1722, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.hass, handler_key, self._hass_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3969, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3955, in _load_integration
    raise data_entry_flow.UnknownHandler from err
homeassistant.data_entry_flow.UnknownHandler

**Comment by myTselection** [comment]
I was using 2025.12.5, which seems incompatible with R4.3.0. After upgrading HA to 2026.1.0 initi works well again.
Might be good to define compatible HA version.
