### ISSUE TITLE
Not working with Home Assistant 2026.2.0

### ISSUE THREAD

**Issue by macdems** [azerty9971/xtend_tuya#731]
Xtend Tuya does not work with Home Assistant 2026.2.0

```
2026-02-05 15:57:24.807 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
```

**Comment by azerty9971** [comment]
Hello,
Can you update to v4.3.1 and retest please?

Thanks,
Azerty

**Comment by macdems** [comment]
It works with v.4.3.1. This release has shown up in HA just minutes ago (after my post).
