### ISSUE TITLE
Error after update to 2026.3.0

### ISSUE THREAD

**Issue by Sn0w82** [azerty9971/xtend_tuya#787]
Got this after update to core 2026.3.0

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 23:38:11 (1 occurrence)
Last logged: 23:38:11

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name 'DPType' from 'homeassistant.components.tuya.const' (/usr/src/homeassistant/homeassistant/components/tuya/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 137, in <module>
    from homeassistant.components.tuya.const import (
    ...<7 lines>...
    )
ImportError: cannot import name 'DPType' from 'homeassistant.components.tuya.const' (/usr/src/homeassistant/homeassistant/components/tuya/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 137, in <module>
    from homeassistant.components.tuya.const import (
    ...<7 lines>...

**Comment by DunLaoghaire1** [comment]
I have the same issue. I hope this will be fixed in due course as it affects lots of my devices and most of my ZigBee lamps cannot be turned on or off. The WiFi lamps still work via the Smart life app though...

**Comment by haydnlj** [comment]
Check the pre-release Beta, fixed for me on 2026.3.0.. upgraded to solve a problem with another integration, but should have known better!

**Comment by azerty9971** [comment]
Hello,
Version 4.3.4 has just been fully released. It should restore full functionality on HA2026.3.

Let me know if you still have issues :).

Have a good day,
Azerty

**Comment by Sn0w82** [comment]
Fixed for me. Thanks for the support and work.

**Comment by darth-aragoth** [comment]
Confirmed, the latest version works on HA 2026.3. Thank you for your support.

**Comment by viorellu** [comment]
Hello! 

Suddenly the values look kinda weird, like I stepped into the Tw/h range:

Sources
Source Usage
Bucatarie 354,510,315.12 kWh
Lumina 28,406,996.86 kWh
Prize 1,114,359,332.84 kWh
Grid total 1,497,276,644.83 kWh

Any idea how to recalibrate these?

Thank you and all the best!

**Comment by maxisamu** [comment]
Yes. Also works for me after updating to 4.3.4.
Fantastic support, thanks so much!

**Comment by viorellu** [comment]
Hello, 

Not sure why but now I get these excessive, TW/h range values in my energy dashboard:

**No longer applies, I did a full reinstall on another HW and everything works fine.**

Thank you for your work and all the best.

**Comment by DunLaoghaire1** [comment]
Same here with the very high values.

I had to restore an OS backup as even the new app update didn't resolve my unresponsive devices

**Comment by diksssdik** [comment]
After updating to the latest patch, the integration began competing with Tuya for authentication. Only one of the Tuya or extndTuya integrations can be functional during each system start.
I assume it's also https://github.com/azerty9971/xtend_tuya/issues/786
Update:
If activate extendTuya after Tuya, everithing seems to work, but you get an error in logs
 custom_components/xtend_tuya/multi_manager/managers/tuya_iot/init.py:205
 Error validating the USER api: False

**Comment by VictorS42** [comment]
Working after update to 4.3.4
