### ISSUE TITLE
Stops working with Core 2026.20b1

### ISSUE THREAD

**Issue by gshafer** [azerty9971/xtend_tuya#723]
Will not load after update to 2026.20b1

**Comment by triptyx-ux** [comment]
for me it also does not work on 2026.1.3
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by azerty9971** [comment]
Hello,
To be able to load XT on HA2026.2 you need to update to the latest beta. (v4.3.1-beta.6)

If you still encounter issues with this version please post your system logs here :).

Thanks in advance!

Have a nice day,
Azerty

**Comment by Jaccer86** [comment]
Updated to the latest beta.6. Unfortunately Xtend Tuya is not loading.
Here the logs:

Logger: homeassistant.util.loop
Bron: util/loop.py:77
Eerst voorgekomen: 20:42:09 (1 gebeurtenis)
Laatst gelogd: 20:42:09

Detected blocking call to import_module with args ('custom_components.xtend_tuya',) in /usr/src/homeassistant/homeassistant/loader.py, line 1078: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

Logger: homeassistant.setup
Bron: setup.py:343
Eerst voorgekomen: 20:42:09 (1 gebeurtenis)
Laatst gelogd: 20:42:09

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_PresetWrapper' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 26, in <module>
    from homeassistant.components.tuya.climate import (
    ...<9 lines>...
    )
ImportError: cannot import name '_PresetWrapper' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 26, in <module>
    from homeassistant.components.tuya.climate import (
    ...<9 lines>...
    )
ImportError: cannot import name '_PresetWrapper' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

**Comment by triptyx-ux** [comment]
just confirmed. 4.3.1 beta6

<img width="575" height="154" alt="Image" src="https://github.com/user-attachments/assets/b85ef026-32e9-47d1-ae6d-6b0c9d82f5b7" />

**Comment by MaikeMota** [comment]
Updating my home assistant to the lastest version solved this problem for me.

**Comment by bradnak** [comment]
Yeah, I just updated to 2026.2.0 from the 2026.1 line (didn't use either HA or integration betas), and got this log output. Hope it helps in getting a fix out quickly.
```
Logger: homeassistant.setup
Source: setup.py:343
First occurred: 08:01:38 (1 occurrence)
Last logged: 08:01:38

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
```

**Comment by ewillner** [comment]
I just updated HA to the released 2026.2.0 and got the same issue of xtend_tuya not loaded.  Updated to 4.3.1 beta9 (the latest beta I see at the moment) and things started normally.  So, working for me.

**Comment by cdmn1** [comment]
2026.2.0 updated to beta9, everything OK so far

**Comment by j4jstyle** [comment]
same issue as above after updating to HA core to 2026.2.0

error : cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover'

**Comment by xydreen** [comment]
> 2026.2.0 updated to beta9, everything OK so far

This also fixed the issue for me.

@j4jstyle if you need this fixed immediately, I recommend doing the above.

**Comment by j4jstyle** [comment]
> > 2026.2.0 updated to beta9, everything OK so far
> 
> This also fixed the issue for me.
> 
> [@j4jstyle](https://github.com/j4jstyle) if you need this fixed immediately, I recommend doing the above.

Thanks, but no Beta9 on beta channels for me :(  ''using HA OS''

Will revert back to 2026.1.3 till an XT fix is done.

EDIT : sorry, tough u where talking about Beta9 release for HA, updated to XT beta9 fixed the issue for me. thanks again

**Comment by dylanpjones** [comment]
The beta version (4.4.1 beta 6) fixed the issues for me. Thank you!

**Comment by Spidy67** [comment]
I can only see 4.3.1 beta 5, which doesn't work. Where are you guys seeing these extra beta versions?

**Comment by EboBH83** [comment]
same thing, i get 3 errors in the logs:
Logger: homeassistant.config_entries
Source: config_entries.py:3969
First occurred: 6:47:38 am (13 occurrences)
Last logged: 6:47:38 am

Error occurred loading flow for integration xtend_tuya: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 6:46:41 am (2 occurrences)
Last logged: 6:47:38 am

Detected blocking call to import_module with args ('custom_components.xtend_tuya',) in /usr/src/homeassistant/homeassistant/loader.py, line 1078: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
Detected blocking call to import_module with args ('custom_components.xtend_tuya.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1307: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 111, in sem_task return await task File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1484, in async_init flow, result = await self._async_init(flow_id, handler, context, data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1522, in _async_init flow = await self.async_create_flow(handler, context=context, data=data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1744, in async_create_flow handler = await _async_get_flow_handler( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3988, in _async_get_flow_handler await _load_integration(hass, domain, hass_config) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3967, in _load_integration await integration.async_get_platform("config_flow") File "/usr/src/homeassistant/homeassistant/loader.py", line 1111, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1101, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1275, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1307, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Logger: homeassistant.setup
Source: setup.py:343
First occurred: 6:46:41 am (1 occurrence)
Last logged: 6:46:41 am

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

**Comment by Spidy67** [comment]
EboBH83 just update to beta 9. If you redownload and select non release, you should see a popup window with available versions.

If like me you dont see beta 9 just hit the up arrow a few times and it should select the top most entry.

For some reason, a lot of the editor windows in HA are terrible and do not scale well in the browser. Anyone find this?

**Comment by jgrjermaine** [comment]
Beta 9 fixed the issue of me too... thank you

**Comment by thorvaldt** [comment]
Beta 9 fixed it here also. Core 2026.2.0

**Comment by azerty9971** [comment]
Hello,
V4.3.1-beta.9 has now been published as the stable release. So no need to do those extra steps to download it manually, just do the update regularly and it should work :).

Have a nice day,
Azerty
