### ISSUE TITLE
Xtend Tuya not starting anymore since upgrade to 2025.8.0

### ISSUE THREAD

**Issue by Jaccer86** [azerty9971/xtend_tuya#459]
As mentioned in the title, after updating to 2025.8.0 (HAOS) the integration fails to start.
Restart didn't help.

Here the related logs:

**1st log**
Logger: homeassistant.setup
Bron: setup.py:343
Eerst voorgekomen: 21:56:17 (1 gebeurtenis)
Laatst gelogd: 21:56:17

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name 'ElectricityTypeData' from 'homeassistant.components.tuya.entity' (/usr/src/homeassistant/homeassistant/components/tuya/entity.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1003, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 17, in <module>
    from .multi_manager.multi_manager import (
    ...<2 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 19, in <module>
    from .shared.shared_classes import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/shared/shared_classes.py", line 14, in <module>
    import custom_components.xtend_tuya.multi_manager.shared.multi_device_listener as mdl
  File "/config/custom_components/xtend_tuya/multi_manager/shared/multi_device_listener.py", line 12, in <module>
    import custom_components.xtend_tuya.util as util
  File "/config/custom_components/xtend_tuya/util.py", line 17, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
        TuyaDPType,
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 104, in <module>
    from homeassistant.components.tuya.entity import (
    ...<5 lines>...
    )
ImportError: cannot import name 'ElectricityTypeData' from 'homeassistant.components.tuya.entity' (/usr/src/homeassistant/homeassistant/components/tuya/entity.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 17, in <module>
    from .multi_manager.multi_manager import (
    ...<2 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/multi_manager.py", line 19, in <module>
    from .shared.shared_classes import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/multi_manager/shared/shared_classes.py", line 14, in <module>
    import custom_components.xtend_tuya.multi_manager.shared.multi_device_listener as mdl
  File "/config/custom_components/xtend_tuya/multi_manager/shared/multi_device_listener.py", line 12, in <module>
    import custom_components.xtend_tuya.util as util
  File "/config/custom_components/xtend_tuya/util.py", line 17, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
        TuyaDPType,
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 104, in <module>
    from homeassistant.components.tuya.entity import (
    ...<5 lines>...
    )
ImportError: cannot import name 'ElectricityTypeData' from 'homeassistant.components.tuya.entity' (/usr/src/homeassistant/homeassistant/components/tuya/entity.py)



**2nd log**
Logger: homeassistant.util.loop
Bron: util/loop.py:77
Eerst voorgekomen: 21:56:17 (1 gebeurtenis)
Laatst gelogd: 21:56:17

Detected blocking call to import_module with args ('custom_components.xtend_tuya',) in /usr/src/homeassistant/homeassistant/loader.py, line 1063: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 156, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by macdems** [comment]
I confirm the problem.

**Comment by quilmore** [comment]
same here (HA via docker, if that's any help to know)

**Comment by tadeu-lima** [comment]
Updated now and I have the exact same issue, running HA OS on Proxmox.

Core - 2025.8.0
Supervisor - 2025.07.3
Operating System - 16.0
Frontend - 20250806.0

**Comment by ewillner** [comment]
Same here.  I restored from my most recent backups and will wait to upgrade - hopefully a fix can some soon.

I noticed in the upgrade announcements (https://www.home-assistant.io/blog/2025/08/06/release-20258/) that there was a Backwards-Incompatible change to Tuya - with more details https://github.com/home-assistant/core/pull/150086.  Not sure if that has any relevance, but I thought I would mention it - if it is helpful.

**Comment by YourYoungerBrothersPug** [comment]
Same here

**Comment by Gferretta** [comment]
Hi 
Same here with 4.1.1

But install 4.1.3 beta 3 pre release and all work fine with HA 2025.8.0

Try it until final fix

**Comment by adynis** [comment]
Based on Azerty's comment, it indeed looks like has been fixed in beta.2 -> https://github.com/azerty9971/xtend_tuya/releases/tag/v4.1.3-beta.2

**Comment by warriornet1** [comment]
I confirm the problem v4.1.2

**Comment by azerty9971** [comment]
I've posted an emergency release to address that issue.
This is technically 4.1.3-beta.2 but as a release so if you were on that version before you can safely update to it, but if you are not yet on 2025.8 and have a lower version I'd wait for 4.1.4 to update since there are still some bugs that need squashing.

I'll try to fix those during this weekend.

Have a nice day,
Azerty

**Comment by warriornet1** [comment]
After updating to version 4.1.3 beta 2, it seems to be working properly. I am waiting for the final version.

**Comment by grouts112** [comment]
4.1.3 is released to fix this.
  goto Hacs and 'redownload' the integration selecting the 4.1.3 release.

**Comment by rtlusciak** [comment]
Carbon Monoxide Alarm Setti+ SS526 is not working with 4.1.3 release. . So as You said I have to wait for the fix more problems with new HA Core.

My config:
Core
2025.8.0
Supervisor
2025.07.3
Operating System
16.0

**Comment by quilmore** [comment]
4.1.3 fixed my issues, thanks

**Comment by jmaliska** [comment]
Since update to HA 2025.8 and then update to xtend_tuya 4.1.3 it doesn't show current power:

<img width="556" height="538" alt="Image" src="https://github.com/user-attachments/assets/59f8a7a0-c6c4-4e93-a291-9837c71e26b7" />

**Comment by AlexBerlin83** [comment]
Here the same problem. The sensors.doesn't work anymore.

![Image](https://github.com/user-attachments/assets/dcdc0f95-b40b-4bd4-92cd-6911eab1ec4c)

**Comment by Jaccer86** [comment]
Here the same. Integration is working again after updating. Thanks for that! 

Unfortunately the power entity from my powersocket is not available anymore.

**Comment by quilmore** [comment]
> Here the same. Integration is working again after updating. Thanks for that!
> 
> Unfortunately the power entity from my powersocket is not available anymore.

I found that in most cases the power attribute was not enabled, a few clicks later and a restart fixed it, not ideal but it's fine

**Comment by avoronkov84** [comment]
Disabled xtend tuya entities seem to be active in some automations - at least i started getting offline reports for these entities that were disabled months ago and they are still disabled. Happened after 4.1.3 is release.

**Comment by cdmn1** [comment]
After HA 2025.8 also had to update to xtend_tuya 4.1.3 which seemed to load OK.

However, after these updates all my tdq Temperature /Humidity sensors stopped working, 

<img width="684" height="173" alt="Image" src="https://github.com/user-attachments/assets/671b4e88-3399-452e-852b-60e5084fc26e" />

<img width="557" height="198" alt="Image" src="https://github.com/user-attachments/assets/b2b56045-62ee-4e12-821f-3c2b5fb48269" />

I use xtendtuya mostly for these sensors.

**Comment by GDXFR** [comment]
Same issue with humidity / temperature sensors.

**Comment by azerty9971** [comment]
this is because the 4.1.3 release was an emergency release to restore basic functionality due to the new HA version, I'm working on it but the fixes take a bit more time than expected, the next release should restore full functionality...

have a nice day,
Azerty

**Comment by azerty9971** [comment]
Hello,
4.1.4 has just been published, this one should fix the issue :).

Can you try and let me know?

Thanks in advance,
Azerty

**Comment by cdmn1** [comment]
Just updated to 4.1.4 and issue remains, tdq temperature/humidity sensors remain unavailable

**Comment by azerty9971** [comment]
Hello,
can you share the device diagnostic or share the device with me on devun999999@gmail.com (EU) or devun999999.us@gmail.com (US)?

Thanks in advance,
Azerty

**Comment by GDXFR** [comment]
Hi, I sent you a diagnostic file.

Edit: i reload the addon and everything is fine now! Thank you again

**Comment by AlexBerlin83** [comment]
Hello, I updated to 4.1.4 and the temperature and humidity sensors were there once. But now they are no longer available.
I've tried reinstalling the integration several times, but I always get the same result.

![Image](https://github.com/user-attachments/assets/cdb09cdf-af24-4058-a6a2-a1f46648a01d)

**Comment by Poiig** [comment]
<img width="845" height="824" alt="Image" src="https://github.com/user-attachments/assets/647edcb5-310d-47e5-a9ac-90514f23cf3f" /> 
I updated to 4.1.4  But now they are no longer available.

**Comment by azerty9971** [comment]
hello,
I'm working on this issue, sorry for the inconvenience.

I expect to have it fixed somewhere around tomorrow.

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
Hello,
Can you try 4.1.5-beta.1?

Have a nice day,
Azerty

**Comment by Poiig** [comment]
> try 4.1.5-beta.1

I tried 4.1.5-beta.1。They are available. Thank You.

<img width="528" height="261" alt="Image" src="https://github.com/user-attachments/assets/21bced8f-56ae-4850-8203-872c15a5d01e" />

**Comment by cdmn1** [comment]
> After HA 2025.8 also had to update to xtend_tuya 4.1.3 which seemed to load OK.
> 
> However, after these updates all my tdq Temperature /Humidity sensors stopped working,
> 
> <img alt="Image" width="684" height="173" src="https://private-user-images.githubusercontent.com/162055081/475946024-671b4e88-3399-452e-852b-60e5084fc26e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxODYyNTQsIm5iZiI6MTc1NTE4NTk1NCwicGF0aCI6Ii8xNjIwNTUwODEvNDc1OTQ2MDI0LTY3MWI0ZTg4LTMzOTktNDUyZS04NTJiLTYwZTUwODRmYzI2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQxNTM5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTQwNTFhZTg0NGIyNjM5ODMxZGFlMDZjZjViNGIwZTgyZGIwODdmYjY1NzdkYWZjM2JlNTE3YzExZTYyYmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a9yeoCIJV1sRnlKyOwVIO8NyAt-0clXiqbYO4ciXSAg"> <img alt="Image" width="557" height="198" src="https://private-user-images.githubusercontent.com/162055081/475946218-b2b56045-62ee-4e12-821f-3c2b5fb48269.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxODYyNTQsIm5iZiI6MTc1NTE4NTk1NCwicGF0aCI6Ii8xNjIwNTUwODEvNDc1OTQ2MjE4LWIyYjU2MDQ1LTYyZWUtNGUxMi04MjFmLTNjMmI1ZmI0ODI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNFQxNTM5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTRjYzU0YTI4Yjg0M2NmZGQ1MGNiMDYwMTkwYmVlNWI4ZDJmYWFhYTBhYjc4ZjYyYWZjNzMxNzk5YWFiNTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KgiAdZjivE-WZL1SurOJO6Tib2z9a9NsQcQyq6uziaQ">
> I use xtendtuya mostly for these sensors.

4.1.5-beta.1 fixed it!

**Comment by Jaccer86** [comment]
> Here the same. Integration is working again after updating. Thanks for that! 
> 
> Unfortunately the power entity from my powersocket is not available anymore. 


Thanks! After updating to 4.1.5-beta.1 the missing power entities are back!

**Comment by AlexBerlin83** [comment]
Perfect. After updating ti 4.1.5 beta, all sensors works again. Y.ou are amazing

**Comment by rtlusciak** [comment]
What about Setti devices? Carbon Monoxide Alarm Setti+ SS526  or Floor Heating Tuya?

**Comment by rtlusciak** [comment]
Nothing??

**Comment by azerty9971** [comment]
Hello,
XT v4.1.5 introduced generic entities that should hopefully implement all the missing entities that you want. Can you go on the device page and check the "disabled entities"?
In theory you should have everything that is supportable in there.
If not feel free to reopen this issue and post a device diagnostic (see https://github.com/azerty9971/xtend_tuya/issues/286)

If some entities are still missing and you are using the regular Tuya integration can you try removing the regular Tuya integration (Settings -> Device and services -> Tuya -> remove all the hubs there) and then restart HA, XT should take over and readd all the entities that were handled by the regular Tuya integration)

Let me know if it worked.

(I'm doing a bit of cleanup in the issue's backlog, that is why I'm closing quite a few of them, but don't hesitate to reopen this one if it still applies ;))

Have a nice day,
Azerty
