### ISSUE TITLE
Stops working with 2026.01

### ISSUE THREAD

**Issue by michael15831** [azerty9971/xtend_tuya#728]
Failed to load integration. Installed 4.3.0

Logger: homeassistant.setup
Quelle: setup.py:343
Erstmals aufgetreten: 09:28:25 (1 Vorkommnis)
Zuletzt protokolliert: 09:28:25

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1038, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1030, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 35, in <module>
    from homeassistant.components.tuya.cover import (
    ...<6 lines>...
    )
ImportError: cannot import name '_IsClosedWrapper' from 'homeassistant.components.tuya.cover' (/usr/src/homeassistant/homeassistant/components/tuya/cover.py)

**Comment by JonathanBout** [comment]
I think the issue title should be 2026.2? If so, I have the same issue
Edit:
Seems like this is a duplicate and this issue has been resolved in the beta version: https://github.com/azerty9971/xtend_tuya/issues/723

**Comment by michael15831** [comment]
You are right, my fault

**Comment by michael15831** [comment]
I installed last available beta update 4.3.1 and everything is ok

**Comment by azerty9971** [comment]
Hello,
V4.3.1-beta.9 has now been published as the stable release. So no need to do those extra steps to download it manually, just do the update regularly and it should work :).

Have a nice day,
Azerty
