### ISSUE TITLE
Setup failed for custom integration 'xtend_tuya' - Version 4.4.1

### ISSUE THREAD

**Issue by bjasiewicz** [azerty9971/xtend_tuya#827]
After upgrade to Version 4.4.1 integration stopped working:

Core: 2026.3.4 

<img width="337" height="150" alt="Image" src="https://github.com/user-attachments/assets/a7f7916e-688a-45b3-8e3a-247fb9f50488" />

Error from LOGS:
Logger: homeassistant.setup
Source: setup.py:343
First occurred: 9:21:03 AM (1 occurrence)
Last logged: 9:21:03 AM

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 25, in <module>
    from homeassistant.components.tuya.climate import (
    ...<5 lines>...
    )
ImportError: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 25, in <module>
    from homeassistant.components.tuya.climate import (
    ...<5 lines>...
    )
ImportError: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

**Comment by fereazo** [comment]
Same here...

Core 2026.3.4

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 10:44:07 AM (1 occurrence)
Last logged: 10:44:07 AM

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 25, in <module>
    from homeassistant.components.tuya.climate import (
    ...<5 lines>...
    )
ImportError: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 25, in <module>
    from homeassistant.components.tuya.climate import (
    ...<5 lines>...
    )
ImportError: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

**Comment by Villi342** [comment]
the same
+

**Comment by mtropper74** [comment]
same error on my system

**Comment by booroondook-eng** [comment]
The same for me.

**Comment by Jumpy07** [comment]
Same here...

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 10:00:37 (1 occurrence)
Last logged: 10:00:37

Setup failed for custom integration 'xtend_tuya': Unable to import component: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 25, in <module>
    from homeassistant.components.tuya.climate import (
    ...<5 lines>...
    )
ImportError: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/xtend_tuya/__init__.py", line 13, in <module>
    from .const import (
    ...<6 lines>...
    )
  File "/config/custom_components/xtend_tuya/const.py", line 11, in <module>
    from .ha_tuya_integration.tuya_integration_imports import (
    ...<4 lines>...
    )
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports.py", line 1, in <module>
    from .tuya_integration_imports_no_cc import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/ha_tuya_integration/tuya_integration_imports_no_cc.py", line 25, in <module>
    from homeassistant.components.tuya.climate import (
    ...<5 lines>...
    )
ImportError: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)

**Comment by DeveloperSzkodziu** [comment]
@Pilot-A320/Guys - How can I return back to previous version? @azerty9971 - can you help?

**Comment by dirkferner** [comment]
Also having issues with loading this Integration, but slightly different error message (much shorter):

Home Assistant Core 2026.4.3

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: homeassistant
Quelle: custom_components/localtuya/discovery.py:67
Integration: LocalTuya integration (Dokumentation, Probleme)
Erstmals aufgetreten: 09:06:45 (1659 Vorkommnisse)
Zuletzt protokolliert: 11:58:37

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (task: None)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/asyncio/selector_events.py", line 1255, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte

**Comment by dirkferner** [comment]
@ DeveloperSzkodziu:
How can I return back to previous version? 

1. Click on the integration card (xtend tuya) in HACS.
2. Click on the three dots icon top right of the page.
3. Select Redownload.
4. Choose the version you want from the dropdown list. ( Most probably the „Last known good“)
5. Click Download.
6. restart HA

**Comment by sharkwsk** [comment]
+1

**Comment by DE-Koodie** [comment]
+1 - i tried the beta version as well as an older version.
I get an error when i try to go back to the old version:
DE "Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}"
EN "The configuration flow could not be loaded: {"message":"Invalid handler specified"}"

**Comment by azerty9971** [comment]
Hello everyone,
You were too quick to update XT ;), this version is meant to be run on the Home Assistant update that comes out in a few hours today ;).

Please do the update to this version when you are about to install the latest stable Home Assistant version (2026.4).
I don't really have a way to make XT versions that are compatible with both HA versions as there has been a ton of changes on the shared library that is used both by the regular Tuya integration and XT.

Also, please try to read the description before doing the update of XT in HACS:
<img width="580" height="666" alt="Image" src="https://github.com/user-attachments/assets/6a8bad68-ac81-4cdc-96c7-40c2e92aa0fc" />

Have a nice day,
Azerty

**Comment by ALERTua** [comment]
Xtend Tuya v4.4.1. Forced redownload and rebooted HA.
Home Assistant 2026.3.4
```
2026-04-01 15:14:34.449 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration xtend_tuya: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
```

So my bad, could have learned to read. Downgrading to 4.3.7

**Comment by azerty9971** [comment]
> Xtend Tuya v4.4.1. Forced redownload and rebooted HA. Home Assistant 2026.3.4
> 
> ```
> 2026-04-01 15:14:34.449 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration xtend_tuya: cannot import name '_TUYA_TO_HA_HVACMODE_MAPPINGS' from 'homeassistant.components.tuya.climate' (/usr/src/homeassistant/homeassistant/components/tuya/climate.py)
> ```
> 
> So my bad, could have learned to read. Downgrading to 4.3.7

;).
I was trying to make sure that people have a stable version to go to when the new HA version comes, didn't think it'd trick that many people to update in advance xD.
You guys are really on the ball when it comes to updating!!

Have a nice day,
Azerty

**Comment by bjasiewicz** [comment]
When it shows, I do click :)
I did roll back and waiting for new HA version - thanks!

**Comment by azerty9971** [comment]
Leaving this one open because a lot of people are opening other issues for the same thing otherwise ;).

I'll close it tomorrow.

Have a nice day,
Azerty

**Comment by dirkferner** [comment]
Updated HA Core to 2026.4 and then updated xtend tuya to current v4.4.1:

Works like charm!

Thanks Azerty

**Comment by Spidy67** [comment]
Seems to be fine here too.

**Comment by lemotor00** [comment]
Same for me, works fine. But now a new HA core update is,out, bumped to 2026.4.1. Will the latest Version  XT work with it or shall I wait for another XT update for it? I'm afraid to get into trouble again like in Match with the consumption data hazard etc.

**Comment by azerty9971** [comment]
Hello,
I just tested and the current version of XT works on HA2026.4.1.

Usually, it's the monthly releases that introduce breaking changes (so next will be HA2026.5).

Have a nice day,
Azerty

**Comment by lemotor00** [comment]
Thanks, will have go.
